const str =   '   when cry no one stays with you when u love no one care u      '
console.log(typeof str)
console.log('========')
console.log('upper case str =', str.toUpperCase(str))
console.log('lower case str =', str.toLowerCase(str))
console.log('index case str =', str.indexOf('el'))
console.log('char of str =', str.charAt(4))
console.log('replace case str =', str.replace('my','karthik'))
console.log('substr str =', str.substr('W',1,1))
console.log('search str =', str.search('rld'))
console.log('trim the str =', str.trim(str))
console.log('concadination =',str.concat('wonderfull'))
console.log(str.split('o'))
console.log(str.split('o',3))