const str =   '   vishnu the play boy zaff fellow    '
console.log(typeof str)
console.log('========')
console.log('upper case str =', str.toUpperCase(str))
console.log('lower case str =', str.toLowerCase(str))
console.log('index case str =', str.indexOf('el'))
console.log('char of str =', str.charAt(4))
console.log('replace case str =', str.replace('my','karthik'))
console.log('substr str =', str.substr('W',1,1))
console.log('search str =', str.search('rld'))
console.log('trim the str =', str.trim(str))
console.log('concadination =',str.concat(' Beautyfull boy '))
console.log(str.split('a'))
console.log(str.split('h',3))